// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
  DB: D1Database;
}

interface Env extends CloudflareEnv {}
