name: 🏠 支援施設追加リクエスト
description: 支援施設の追加リクエスト
title: "[施設]: "
body:
  - type: markdown
    attributes:
      value: |
        支援施設の追加にご協力いただき、ありがとうございます。
        以下の情報を記入してください。

  - type: input
    id: name
    attributes:
      label: 支援施設名
      description: 支援施設の名前を記入してください。
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 支援施設の種類
      description: 支援施設の種類を記入してください（この中にない場合は未選択）
      options:
        - 入浴施設
        - 送迎バス
        - 食事提供
        - 宿泊施設
        - 学習施設
    validations:
      required: false

  - type: textarea
    id: address
    attributes:
      label: 支援施設の住所
      description: 支援施設の住所を記入してください。
    validations:
      required: false

  - type: textarea
    id: phone
    attributes:
      label: 支援施設の電話番号
      description: 支援施設の電話番号を記入してください。
    validations:
      required: false

  - type: textarea
    id: hours
    attributes:
      label: 支援施設の営業時間
      description: 支援施設の営業時間を記入してください。
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: 支援施設の詳細
      description: 支援施設の詳細を記入してください。
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 補足情報
      description: 支援施設の補足情報を記入してください。
    validations:
      required: false

  - type: input
    id: mapUrl
    attributes:
      label: 支援施設の Google Maps URL
      description: 支援施設の Google Maps URLを記入してください。該当施設を選択して共有ボタンから発行されるURLを記入してください。
    validations:
      required: false

  - type: input
    id: coordinates
    attributes:
      label: 支援施設の座標
      description: Google Maps で該当施設を最大まで拡大して、地点を右クリックして出てきたポップアップの座標を記入してください。
    validations:
      required: false
